[tool.pytest.ini_options]
filterwarnings = [
    "error::DeprecationWarning",
    "error::modal.exception.DeprecationError",
    "ignore::DeprecationWarning:pytest.*:",
]
pythonpath = [
]

[tool.black]
line-length = 80

[tool.isort]
known_first_party="modal"
extra_standard_library="pytest"
profile="black"


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
no_strict_optional = true

# https://github.com/python/mypy/issues/10632
[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true

[tool.ruff]
# TODO: Add when available: "E266", "E203"
ignore = ["E501","E741","E402"]
exclude = [
    ".venv",
    "venv",
    "__pycache__",
]
select = ['E', 'F', 'W', 'I']

[tool.ruff.isort]
combine-as-imports = true
known-third-party = []

[tool.setuptools]
py_modules = ["core.*"]
[tool.setuptools.packages.find]
where = ["."]
include = ["core.*"]
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[project]
name = 'vidify'
version = "1.0.0"
